version: '3.8'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./etc/data:/data
      - ./etc/letsencrypt:/etc/letsencrypt
    networks:
      - ball-network
  db:
    image: postgres
    container_name: ball_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - ball-network
  api:
    build: ./IEAM-Backend
    container_name: ball_api
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./IEAM-Backend:/opt/app/api 
    depends_on:
      - db
    networks:
      - ball-network
  web:
    build:
      context: ./IEAM-Frontend
      dockerfile: Dockerfile
    container_name: ball_frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - ball-network
    command: 'npm run prod'
volumes:
  db:
    driver: local

networks:
  ball-network:
    driver: bridge
